### ISSUE TITLE
Allow compilation without needing a connection

### ISSUE THREAD

**Issue by bafonso** [axoloti/axoloti#374]
It would be nice to be able to compile your patch in order to make sure things work without having to have the axoloti connected. Is it using the axoloti during the compilation?

I ran into this issue while making some code to process MIDI.

**Comment by TheTechnobear** [comment]
you can do this already.
edit the axoloti.prefs and set expert mode = true.
then you will find a compile option on the patch menu.
(this is a hidden option, since we do not want users to accidentally believe this is a required step)

p.s. id suggestion posting questions/issues initially on community.axoloti.com before here, so it can be discussed/commented on their... this is useful of other users can benefit from responses if they have similar questions. (I think this has actually been asked before there)
