### ISSUE TITLE
adcvalues[2], adcvalues[3] - not updating

### ISSUE THREAD

**Issue by TheTechnobear** [axoloti/axoloti#451]
Ive a thonk axo control which uses alot of IO,  and found 2 potentiometers are not working
the ones that use adcvalues[2], adcvalues[3] 

all other values pots work fine.

**Comment by TheTechnobear** [comment]
confirmed with gpio/in/analog PA2 and PA3 do not appear to work.

**Comment by JohannesTaelman** [comment]
Pin modes for PA2 and PA2 were not set to analog input on bootup, fixed in 09eae30 
Additionally, since multiple patches can run, gpio pin modes are no longer initialized by firmware when starting a patch, as that could disrupt a running patch.
Factory objects are updated to restore pin modes to analog input on object dispose.
